server:
  port: 9000

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: jwt-user-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
